coverage:
  status:
    project:
      default: false
      tests:
        target: 0%
        paths:
          - "tests/"
      caproto:
        target: auto
        threshold: 1%
        paths:
          - "caproto/"
          - "!caproto/generate_headers.py"
          - "!caproto/_version.py"
