# This file auto-generated by `generate_commands.py`.
# Do not modify this file directly.
import struct

{% for command in commands %}

def {{command.name}}({{ command.input_params|map('attr', 'field')|join(', ') }}):
    """
    {% for param in input_params %}
      {{ param.field }} :
          {{ param.description }}
    {% endfor %}
    """
    struct_args = ({{ command.struct_args|map('repr')|join(', ') }})
    return struct.pack('HHHHII', *struct_args)

{% endfor %}
