# This file auto-generated by `generate_commands.py`.
# Do not modify this file directly.
import struct

{% for command in commands %}

def {{command.name}}({{ command.input_params|map('attr', 'field')|join(', ') }}):
    """
{{ command.description }}

    Parameters
    ----------
    {% for param in command.input_params %}
      {{ param.field }} : integer
          {{ param.description }}
    {% endfor %}
    """
    struct_args = ({{ command.struct_args|join(', ') }})
    return struct.pack('HHHHII', *struct_args)

{% endfor %}
