# This file auto-generated by `generate_dbr_types.py`.
# Do not modify this file directly.
import ctypes


{% for name, fields in dbr_types.items() %}
class {{name}}(ctypes.BigEndianStructure):
    _fields_ = [{% for field_name, field_type in fields.items() %}
        ('{{ field_name }}', {{ field_type }}),{% endfor %}
    ]
{% endfor %}
